#!/usr/bin/env ruby
# frozen_string_literal: true

require_relative "lib/cask_updater"

CONFIG = CaskUpdater::Config.new(
  token: "codexplusplus",
  repository: "BigPizzaV3/CodexPlusPlus",
  asset_prefix: "CodexPlusPlus",
  extension: "dmg",
  cask_path: File.expand_path("../Casks/codexplusplus.rb", __dir__),
)

exit CaskUpdater.cli(CONFIG) if __FILE__ == $PROGRAM_NAME
